config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :cakes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cake.rb
class Cake < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_name_and_description, against: {
    name: 'A',
    description: 'B'
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cake
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :mince_pie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cake
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  def index
    if params[:query].present?
      @cakes = Cake.search_by_name_and_description(params[:query])
    else
      @cakes = Cake.all
    end
  end

  def show
    @cake = Cake.find(params[:id])
  end

  def new
    @cake = Cake.new
  end

  def create
    @cake = Cake.new(cake_params)
    if @cake.save
      redirect_to @cake
    else
      render 'new'
    end
  end

  private

  def cake_params
    params.require(:cake).permit(:name, :description, :image, :price, :taste, :overall_rating)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment.cake
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :cake_id, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @rating = Rating.new
  end

  def create
    @rating = Rating.new(rating_params)
    if @rating.save
      redirect_to @rating.cake
    else
      render 'new'
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:user_id, :cake_id, :price_rating, :taste_rating, :overall_rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cakes/index.html.erb
<div class="container-fluid">
  <h1>Cakes</h1>

  <div class="cake-cards">
    <% @cakes.each do |cake| %>
      <div class="cake-card">
        <img src="<%= cake.image_url %>" alt="<%= cake.name %>">
        <div class="cake-details">
          <h2><%= link_to cake.name, cake %></h2>
          <div class="cake-text">
            <p>Price: <%= number_to_currency(cake.price) %></p>
            <p>Taste: <%= cake.taste %></p>
            <p>Overall Rating: <%= cake.overall_rating %></p>
          </div>
          <div class="actions">
            <%= link_to 'Edit', edit_cake_path(cake) %>
            <%= link_to 'Delete', cake, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to 'New Mince cake', new_cake_path %>
</div>

app/views/cakes/show.html.erb
<h1><%= @cake.name %></h1>

<p><strong>Description:</strong> <%= @cake.description %></p>
<p><strong>Price:</strong> <%= number_to_currency(@cake.price) %></p>

<%= link_to 'Back to Cakes', cakes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateThecake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
      <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid">
<!-- Search Bar -->
  <div class="search">
    <%= form_with(url: cakes_path, method: 'get') do |form| %>
      <%= form.text_field :query, placeholder: 'Search Cakes' %>
      <%= form.submit 'Search' %>
    <% end %>
  </div>
  <div class="home-image">
    <img src="/assets/_5432dd8b-d909-4265-9777-32921ab9f5e3.jpeg" alt="Giant mince pie with opinions popping out of it">
  </div>

  <div>
    <%= link_to "Log in", user_session_path, class: "button-small" %>
    <%= link_to "Sign up", new_user_registration_path, class: "button-small" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mobile-footer">
  <p>&copy; <%= Time.now.year %> Rate the cake</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="mobile-navbar">
  <div class="nav-left">
    <%= link_to "Home", root_path %>
  </div>
  <div class="nav-right">
    <%= link_to "Login", user_session_path %>
  </div>
</nav>